import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { StudioStore, uuid } from '../src/server/studio/store';
import { ResearchCollector } from '../src/server/studio/collector';
import { DEFAULT_FILTERS } from '../src/services/config';
import type { ResearchContext } from '../src/services/studio-contracts';
const context: ResearchContext = {filters:{...DEFAULT_FILTERS,source:'NSW'},metric:'crashes',notes:'',references:''};
function setup(){ const dir=mkdtempSync(join(tmpdir(),'arsia-research-contract-')); const store=new StudioStore(join(dir,'research.sqlite')); return {store,close(){store.close();rmSync(dir,{recursive:true,force:true});}}; }
function act(store:StudioStore,id:string,a:Record<string,unknown>){ return store.action(id,{...a,revision:store.get(id).revision}); }
test('a committed complete run survives a late collector transport error',async()=>{const x=setup();try{const s=x.store.create('Lifecycle',context); const b=x.store.beginRun(s.id,uuid(),'Inspect'); const c=new ResearchCollector(x.store,s.id,b.run); await c.accept({type:'message',text:'Observed result',simulated:false});await c.accept({type:'done',model:'explicit zero-model fixture'});c.persist();await c.accept({type:'error',code:'NETWORK',message:'Late connection failure'});c.persist();assert.equal(x.store.get(s.id).runs[0].status,'complete');}finally{x.close();}});
test('duplicate run request is read-only and does not increase revision',()=>{const x=setup();try{const s=x.store.create('Idempotent',context);const key=uuid();x.store.beginRun(s.id,key,'Question');const before=x.store.get(s.id);x.store.beginRun(s.id,key,'Question');assert.equal(x.store.get(s.id).revision,before.revision);const originalRead=x.store.runRequest.bind(x.store);x.store.runRequest=()=>undefined;assert.equal(x.store.beginRun(s.id,key,'Question').replay,true);assert.equal(x.store.get(s.id).revision,before.revision);x.store.runRequest=originalRead;}finally{x.close();}});
test('manual finding records independent checks, then invalidates review on changed text',()=>{const x=setup();try{let s=x.store.create('Findings',context);s=act(x.store,s.id,{type:'finding',kind:'Observation',title:'A statement',explanation:''});let f=s.findings[0];assert.equal(f.checks?.evidenceLinked,false);assert.equal(f.checks?.numericChecked,false);s=act(x.store,s.id,{type:'finding_review',id:f.id});assert.equal(s.findings[0].checks?.userReviewed,true);s=act(x.store,s.id,{type:'finding',id:f.id,title:'A revised statement'});f=s.findings[0];assert.equal(f.checks?.userReviewed,false);assert.equal(f.checks?.reviewNeeded,true);assert.equal(f.edits.at(-1)?.checks?.userReviewed,true);}finally{x.close();}});

import { runAgent, type ModelStream } from '../src/server/agent/runner';
import { loadOfficialSnapshot, createOfficialProvider } from '../src/server/official-data';
import { executeAnalysisTool } from '../src/server/agent/tools';
import { evidenceReference, prepareResearchDraft, validateResearchDraft, validateStudyReport } from '../src/server/studio/research-contract';
import { saveResource } from '../src/server/studio/resources';
import type { ResponseStreamEvent, ResponseOutputItem } from 'openai/resources/responses/responses';
async function queryRun(store:StudioStore,studyId:string){
 const {run}=store.beginRun(studyId,uuid(),'Inspect recorded counts');
 const snapshot=await loadOfficialSnapshot();const params={source:null,dateRange:null};
 const result=await executeAnalysisTool('core_metrics',params,{page:'/studio',filters:context.filters},createOfficialProvider(snapshot),snapshot);
 const c=new ResearchCollector(store,studyId,run);
 await c.accept({type:'evidence',evidence:{id:'E1',title:'Source counts',description:'Actual hash-verified snapshot query',result,query:{tool:'core_metrics',parameters:params,requestedContext:{page:'/studio',filters:context.filters},assurance:{parameters:'validated',execution:'returned',claims:'not_automatically_verified'}}}});
 await c.accept({type:'done',model:'zero-model host fixture'});return c.persist();
}
const draftBlock=(text:string,citations:unknown[]=[])=>({kind:'text',text,runId:null,refId:null,caption:null,citations});
function draftStream(output:unknown,seen:(p:Parameters<ModelStream>[0])=>void=()=>{}):ModelStream{return async (params)=>{seen(params);return (async function*(){yield {type:'response.output_text.delta',delta:JSON.stringify(output)} as ResponseStreamEvent;yield {type:'response.completed',response:{status:'completed',output:[],usage:{input_tokens:0,output_tokens:0,total_tokens:0}}} as unknown as ResponseStreamEvent;})();};}
test('numerical claim checks are exact and separate from user review; edit and evidence changes retain history',async()=>{const x=setup();try{let s=await queryRun(x.store,x.store.create('Numerical findings',context).id);const runId=s.runs[0].id;const claim={evidenceId:'E1',pointer:'/results/0/data/crashes/value',source:'NSW',metric:'crashes',from:context.filters.dateRange.from,to:context.filters.dateRange.to,value:92082,unit:'crashes'};s=act(x.store,s.id,{type:'finding',kind:'Observation',title:'Recorded crashes',explanation:'A count, not a causal explanation.',runId,evidenceIds:['E1'],claims:[claim]});const original=structuredClone(s.findings[0]);assert.equal(original.checks?.numericChecked,true);assert.equal(original.checks?.userReviewed,false);s=act(x.store,s.id,{type:'finding_review',id:original.id});assert.equal(s.findings[0].checks?.userReviewed,true);s=act(x.store,s.id,{type:'finding',id:original.id,title:'Different count',claims:[{...claim,value:0}]});assert.equal(s.findings[0].checks?.numericChecked,false);assert.equal(s.findings[0].checks?.unsupportedClaim,true);assert.equal(s.findings[0].edits.at(-1)?.checks?.numericChecked,true);s=act(x.store,s.id,{type:'finding',id:original.id,claims:[claim]});assert.equal(s.findings[0].checks?.numericChecked,false);s=act(x.store,s.id,{type:'finding_check',id:original.id});assert.equal(s.findings[0].checks?.numericChecked,true);s=act(x.store,s.id,{type:'finding',id:original.id,claims:[{...claim,unit:'percent'}]});s=act(x.store,s.id,{type:'finding_check',id:original.id});assert.equal(s.findings[0].checks?.numericChecked,false);assert.equal(original.checks?.numericChecked,true);}finally{x.close();}});
test('resource row claims verify immutable source, metric, unit, dates and selected plotted value',async()=>{const x=setup();try{let s=await saveResource(x.store,{requestId:uuid(),definitionId:'trend',context,query:{granularity:'yearly'}});const run=s.runs[0],asset=run.resource!,row=run.views[0].rows[0];const claim={evidenceId:'E1',pointer:'/rows/0/value',source:row.source,metric:row.metric,from:row.from??context.filters.dateRange.from,to:row.to??context.filters.dateRange.to,value:row.value,unit:row.unit??asset.unit};s=act(x.store,s.id,{type:'finding',title:'The selected annual count',kind:'Observation',runId:run.id,evidenceIds:['E1'],claims:[claim]});assert.equal(s.findings[0].checks?.numericChecked,true);assert.equal(s.findings[0].origin,'user');s=act(x.store,s.id,{type:'finding',id:s.findings[0].id,claims:[{...claim,from:context.filters.dateRange.from,to:context.filters.dateRange.to}]});s=act(x.store,s.id,{type:'finding_check',id:s.findings[0].id});assert.equal(s.findings[0].checks?.numericChecked,false,'one annual row is not the whole five-year scope');s=act(x.store,s.id,{type:'finding',id:s.findings[0].id,claims:[{...claim,source:'Different source'}]});s=act(x.store,s.id,{type:'finding_check',id:s.findings[0].id});assert.equal(s.findings[0].checks?.numericChecked,false);}finally{x.close();}});
test('Draft and Revise use the real runner/collector/store with an explicit zero-model stream and no fresh query',async()=>{const x=setup();try{let s=await queryRun(x.store,x.store.create('Draft modes',context).id);const sourceRun=s.runs[0];s=act(x.store,s.id,{type:'block_add',kind:'text',text:'Original paragraph'});s=act(x.store,s.id,{type:'block_add',kind:'text',text:'Unselected paragraph'});for(const mode of ['draft','revise'] as const){const targetBlockId=mode==='revise'?s.report[0].id:undefined;const prepared=prepareResearchDraft(s,mode,[sourceRun.id],targetBlockId);const b=x.store.beginRun(s.id,uuid(),'Rephrase saved evidence',false,undefined,{mode,selectedRunIds:[sourceRun.id],targetBlockId});const c=new ResearchCollector(x.store,s.id,b.run);let requests=0;const output={blocks:[draftBlock(mode==='draft'?'The saved source has 92082 recorded crashes.':'The source records 92082 crashes.',[prepared.refs[0]])]};for await(const event of runAgent({context:{page:'/studio',filters:context.filters},message:b.run.question,history:[]},{model:'zero-model-fixture',signal:new AbortController().signal,stream:draftStream(output,p=>{requests++;assert.equal(p.tool_choice,'none');assert.deepEqual(p.tools,[]);assert.ok(p.text?.format);assert.match(String(p.instructions),/saved materials/);}),research:{mode,notes:'',references:'',skipPresentation:()=>false,draft:{materials:prepared.materials,validate:v=>validateResearchDraft(x.store.get(s.id),prepared,v)}}})){await c.accept(event);}s=c.persist();assert.equal(requests,1);assert.equal(c.run.status,'complete');assert.equal(c.run.reportDraft?.status,'proposed');const before=structuredClone(s.report);s=act(x.store,s.id,{type:'report_apply',runId:c.run.id,draftId:c.run.reportDraft!.id});assert.equal(s.runs.at(-1)?.reportDraft?.status,'applied');if(mode==='revise')assert.deepEqual(s.report.slice(1),before.slice(1));else {s=act(x.store,s.id,{type:'block_add',kind:'text',text:'Unselected paragraph'});}assert.equal(s.runs[0].evidence[0].id,sourceRun.evidence[0].id);}assert.equal(x.store.versions(s.id).filter(v=>v.label==='Before applying report draft').length,2);}finally{x.close();}});
test('draft validation rejects unknown fields, wrong hashes, unselected/cross-study citations and out-of-target revisions',async()=>{const x=setup();try{let s=await queryRun(x.store,x.store.create('Own',context).id);const other=await queryRun(x.store,x.store.create('Other',context).id);const prepared=prepareResearchDraft(s,'draft',[s.runs[0].id]);const ref=prepared.refs[0];for(const bad of [{blocks:[{...draftBlock('Text'),script:'alert(1)'}]},{blocks:[draftBlock('92082',[{...ref,resultHash:'0'.repeat(64)}])]},{blocks:[draftBlock('92082',[evidenceReference(other,other.runs[0].id,'E1')])]},{blocks:[draftBlock('92082')]},{blocks:[{...draftBlock('A title'),kind:'resource',runId:other.runs[0].id,refId:'E1'}]}])assert.throws(()=>validateResearchDraft(s,prepared,bad));assert.throws(()=>prepareResearchDraft(s,'draft',[other.runs[0].id]));s=act(x.store,s.id,{type:'block_add',kind:'text',text:'Target'});const revise=prepareResearchDraft(s,'revise',[s.runs[0].id],s.report[0].id);assert.throws(()=>validateResearchDraft(s,revise,{blocks:[draftBlock('A'),draftBlock('B')]}),/only the selected/);assert.throws(()=>validateResearchDraft(s,revise,{blocks:[{...draftBlock('A'),kind:'section'}]}),/cannot change/);}finally{x.close();}});
test('draft apply is conflict-safe, report-only undo preserves analyses, and stale result hashes block formal export',async()=>{const x=setup();try{let s=await queryRun(x.store,x.store.create('Report conflict',context).id);s=act(x.store,s.id,{type:'report_template',metadata:{template:'brief',language:'en'}});const original=structuredClone(s.report);const prepared=prepareResearchDraft(s,'draft',[s.runs[0].id]);const b=x.store.beginRun(s.id,uuid(),'Draft',false,undefined,{mode:'draft'});b.run.reportDraft=validateResearchDraft(s,prepared,{blocks:[draftBlock('Draft text')]});b.run.status='complete';s=x.store.updateRun(s.id,b.run);const savedRevision=s.revision;s=act(x.store,s.id,{type:'block_edit',id:s.report[1].id,text:'Concurrent edit'});assert.throws(()=>x.store.action(s.id,{type:'report_apply',runId:b.run.id,draftId:b.run.reportDraft!.id,revision:savedRevision}),/changed/);assert.throws(()=>act(x.store,s.id,{type:'report_apply',runId:b.run.id,draftId:b.run.reportDraft!.id}),/report changed/);assert.equal(x.store.get(s.id).report[1].text,'Concurrent edit');const snap=act(x.store,s.id,{type:'snapshot',label:'Report only restore'});const version=x.store.versions(s.id).find(v=>v.label==='Report only restore')!;s=act(x.store,s.id,{type:'block_edit',id:s.report[1].id,text:'Next edit'});const runCount=s.runs.length;s=act(x.store,s.id,{type:'report_undo',versionId:version.id});assert.deepEqual(s.report,snap.report);assert.equal(s.runs.length,runCount);assert.equal(original.length,s.report.length);s=act(x.store,s.id,{type:'block_add',kind:'evidence',runId:s.runs[0].id,refId:'E1'});const tampered=structuredClone(s);(tampered.runs[0].evidence[0].result as Record<string,unknown>).tamper=true;assert.throws(()=>validateStudyReport(tampered),/hash/);}finally{x.close();}});
test('terminal failed/stopped attempts cannot be promoted by late done; retries retain old results and alias replay is read-only',async()=>{const x=setup();try{const s=x.store.create('Stop',context);let b=x.store.beginRun(s.id,uuid(),'Question');const c=new ResearchCollector(x.store,s.id,b.run);await c.accept({type:'message',text:'Partial result',simulated:false});await c.accept({type:'error',code:'QUERY',message:'Query stopped'});await c.accept({type:'done',model:'fixture'});assert.equal(c.persist().runs[0].status,'failed');const old=structuredClone(c.run);const retryKey=uuid();b=x.store.beginRun(s.id,retryKey,'Retry',false,c.run.id);assert.equal(b.run.previousAttempts[0].answer,'Partial result');const before=x.store.get(s.id);assert.equal(x.store.runRequest(s.id,retryKey)?.run.attempt,2);assert.equal(x.store.get(s.id).revision,before.revision);old.status='complete';x.store.updateRun(s.id,old);assert.equal(x.store.get(s.id).runs[0].attempt,2);assert.equal(x.store.get(s.id).runs[0].status,'running');b.run.status='stopped';x.store.updateRun(s.id,b.run);b.run.status='complete';assert.equal(x.store.updateRun(s.id,b.run).runs[0].status,'stopped');}finally{x.close();}});
test('Explore/Analyze retain actual query and checked-evidence tool loop under zero-model transport',async()=>{const x=setup();try{const snapshot=await loadOfficialSnapshot();for(const mode of ['explore','analyze'] as const){const s=x.store.create(mode,context);const b=x.store.beginRun(s.id,uuid(),'Inspect counts',false,undefined,{mode});const c=new ResearchCollector(x.store,s.id,b.run);let count=0;const stream:ModelStream=async params=>(async function*(){assert.match(String(params.instructions),new RegExp(`${mode} mode`));if(count++===0)yield {type:'response.completed',response:{status:'completed',output:[{type:'function_call',name:'core_metrics',arguments:JSON.stringify({source:null,dateRange:null}),call_id:'stub-call'}]}} as unknown as ResponseStreamEvent;else{yield {type:'response.output_text.delta',delta:'The source records 92082 crashes [E1].'} as ResponseStreamEvent;yield {type:'response.completed',response:{status:'completed',output:[{type:'message',content:[]} as unknown as ResponseOutputItem]}} as unknown as ResponseStreamEvent;}})();for await(const event of runAgent({context:{page:'/studio',filters:context.filters},message:b.run.question,history:[]},{model:'zero-model-fixture',signal:new AbortController().signal,service:createOfficialProvider(snapshot),snapshot,stream,research:{mode,notes:'',references:'',skipPresentation:()=>false}}))await c.accept(event);const result=c.persist();assert.equal(result.runs[0].status,'complete');assert.equal(result.runs[0].evidence[0].query?.tool,'core_metrics');assert.equal(count,2);}}finally{x.close();}});

test('atomic findings from one run preserve independent claims and historical report bindings after context changes',async()=>{const x=setup();try{let s=await queryRun(x.store,x.store.create('Atomic findings',context).id);const run=s.runs[0];const base={evidenceId:'E1',source:'NSW',from:context.filters.dateRange.from,to:context.filters.dateRange.to};for(const item of [{kind:'Observation',title:'Recorded crash count',metric:'crashes',unit:'crashes',value:92082},{kind:'Hypothesis',title:'A possible explanation still requires investigation',metric:'fatalCrashes',unit:'fatal crashes',value:1388}])s=act(x.store,s.id,{type:'finding',kind:item.kind,title:item.title,explanation:'The selected count does not establish a causal explanation.',runId:run.id,evidenceIds:['E1'],claims:[{...base,metric:item.metric,unit:item.unit,value:item.value,pointer:`/results/0/data/${item.metric}/value`}]});assert.equal(s.findings.length,2);assert.notEqual(s.findings[0].id,s.findings[1].id);assert.notEqual(s.findings[0].claims![0].pointer,s.findings[1].claims![0].pointer);assert.equal(s.findings[1].kind,'Hypothesis');assert.equal(s.findings[1].checks?.numericChecked,true,'specified number only, not hypothesis truth');assert.equal(s.findings[1].checks?.userReviewed,false);assert.equal(s.findings[1].checks?.reviewNeeded,true);assert.match(s.findings[1].checks!.notes.join(' '),/causal claims remain unverified/);s=act(x.store,s.id,{type:'block_add',kind:'finding',refId:s.findings[0].id});const before=structuredClone({findings:s.findings,report:s.report,runs:s.runs});s=act(x.store,s.id,{type:'context',context:{...context,filters:{...context.filters,source:'VIC'}}});assert.equal(s.context.filters.source,'VIC');assert.deepEqual(s.findings,before.findings);assert.deepEqual(s.report,before.report);assert.deepEqual(s.runs,before.runs);validateStudyReport(s);const saved=x.store.version(s.id,x.store.versions(s.id)[0].id);assert.deepEqual(saved.findings,before.findings);assert.deepEqual(saved.report,before.report);const local=x.store.get(s.id);local.context.filters.source='changed only in caller memory';assert.equal(x.store.version(s.id,x.store.versions(s.id)[0].id).findings[0].context.filters.source,'NSW');}finally{x.close();}});
test('structured draft applies legal sections and saved resource references through runner and rejects executable output',async()=>{const x=setup();try{let s=await saveResource(x.store,{requestId:uuid(),definitionId:'severity',context});const resourceRun=s.runs[0],prepared=prepareResearchDraft(s,'draft',[resourceRun.id]);const output={blocks:[{...draftBlock('Results'),kind:'section'},{kind:'resource',text:'Source-native severity distribution',runId:resourceRun.id,refId:resourceRun.resource!.id,caption:'Recorded crashes in the saved source period.',citations:prepared.refs}]};assert.throws(()=>validateResearchDraft(s,prepared,{blocks:[draftBlock('<script>bad()</script>')]}),/Executable markup/);const begun=x.store.beginRun(s.id,uuid(),'Draft results from the selected saved chart',false,undefined,{mode:'draft',selectedRunIds:[resourceRun.id]});const collector=new ResearchCollector(x.store,s.id,begun.run);for await(const event of runAgent({context:{page:'/studio',filters:context.filters},message:begun.run.question,history:[]},{model:'explicit-zero-model-fixture',signal:new AbortController().signal,stream:draftStream(output),research:{mode:'draft',notes:'',references:'',skipPresentation:()=>false,draft:{materials:prepared.materials,validate:value=>validateResearchDraft(x.store.get(s.id),prepared,value)}}}))await collector.accept(event);s=collector.persist();const proposed=s.runs.at(-1)!;assert.equal(proposed.status,'complete');assert.equal(proposed.reportDraft?.blocks[1].resultHash?.length,64);s=act(x.store,s.id,{type:'report_apply',runId:proposed.id,draftId:proposed.reportDraft!.id});assert.deepEqual(s.report.map(b=>b.kind),['section','resource']);assert.equal(s.report[1].refId,resourceRun.resource!.id);assert.equal(s.report[1].citations![0].resultHash,prepared.refs[0].resultHash);assert.equal(validateStudyReport(s).length,2);assert.deepEqual(s.runs[0],JSON.parse(JSON.stringify(resourceRun)), 'the persisted JSON snapshot keeps all serialized source facts');}finally{x.close();}});
