import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
test.beforeEach(async ({ page }) => { await page.emulateMedia({ reducedMotion: "reduce" }); });
const batch = "bcc5da57-25f2-41ec-9925-bef421b02671";
const scope = (path = "/", from = "2024-01-01", to = "2024-12-31", extra = "") => `${path}?source=NSW&from=${from}&to=${to}&batchId=${batch}&datasetVersion=official-v1${extra}`;
test("partial-year evidence and actual Overview JSON download retain month scope", async ({ page }) => {
  await page.goto(scope("/", "2024-03-01", "2024-03-31"));
  await expect(page.getByText("Recorded crashes · Mar 2024", {exact:true})).toBeVisible();
  await expect(page.locator(".metric-value").first()).toHaveText("1,601");
  await page.getByRole("button", { name: "Trend chart evidence" }).click();
  await expect(page.getByRole("dialog")).toContainText("2024 · Mar subtotal (1/1 months)");
  await page.keyboard.press("Escape");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", {name:"Export",exact:true}).click();
  const download = await downloadPromise;
  await download.saveAs("output/playwright/overview-march.json");
  const data = JSON.parse(await readFile((await download.path())!, "utf8"));
  expect(data.filters.dateRange).toEqual({from:"2024-03-01",to:"2024-03-31"});
  expect(data.overview.data.crashes.value).toBe(1601);
  expect(data.timeSeries.data[0]).toMatchObject({ selectedMonths:[3], observedMonths:1, fullYear:false });
  await page.getByRole("link", { name: "Compare matching months in Analytics" }).click();
  await expect(page).toHaveURL(/\/analytics\?.*from=2024-03-01/);
  await expect(page.getByRole("heading", {name:"Mar 2024 details"})).toBeVisible();
  await expect(page.getByRole("heading", {name:"Typical month"})).toHaveCount(0);
});
test("metric-linked comparison, refresh, back-forward and Analytics download", async ({ page }) => {
  await page.goto(scope("/analytics"));
  await expect(page.getByText("+1.2%", {exact:true})).toBeVisible();
  await page.getByRole("region", {name:"Time and change"}).getByRole("button", {name:"Lives lost",exact:true}).click();
  await expect(page.getByRole("heading", {name:"Lives lost year-on-year"})).toBeVisible();
  await expect(page.getByText("-3.8%", {exact:true})).toBeVisible();
  await expect(page).toHaveURL(/metric=livesLost/);
  await page.reload();
  await expect(page.getByText("-3.8%", {exact:true})).toBeVisible();
  await page.getByRole("region", {name:"Time and change"}).getByRole("button", {name:"Fatal crashes",exact:true}).click();
  await expect(page.getByText("-1.7%", {exact:true})).toBeVisible();
  await page.goBack();
  await expect(page.getByRole("region", {name:"Time and change"}).getByRole("button", {name:"Lives lost",exact:true})).toHaveAttribute("aria-pressed","true");
  await page.goForward();
  await expect(page.getByRole("region", {name:"Time and change"}).getByRole("button", {name:"Fatal crashes",exact:true})).toHaveAttribute("aria-pressed","true");
  const pending = page.waitForEvent("download");
  await page.getByRole("button", {name:"Export",exact:true}).click();
  const exportFile = await pending; await exportFile.saveAs("output/playwright/analytics-four-metrics.json");
  const result = JSON.parse(await readFile((await exportFile.path())!,"utf8"));
  expect(result.view.metric).toBe("fatalCrashes");
  expect(result.analysis.data.yearly[0].comparisons.livesLost).toMatchObject({current:327,previous:340});
});
test("new tabs restore a pinned LGA and invalid identity is explicitly blocked", async ({ page, context }) => {
  const url = scope("/analytics", "2024-03-01", "2024-03-31", "&regionId=17200&metric=livesLost&interval=yearly");
  await page.goto(url);
  await expect(page.getByTestId("analytics-total")).toHaveText("59");
  const second = await context.newPage(); await second.goto(page.url());
  await expect(second.getByTestId("analytics-total")).toHaveText("59");
  await expect(second.getByRole("region", {name:"Time and change"}).getByRole("button", {name:"Lives lost",exact:true})).toHaveAttribute("aria-pressed","true");
  await second.goto("/analytics?batchId=missing-batch");
  await expect(second.locator(".error-banner")).toContainText("not available");
  await expect(second.getByTestId("analytics-total")).toHaveCount(0);
  await second.getByRole("button",{name:"Open supported snapshot"}).click();
  await expect(second.getByTestId("analytics-total")).toHaveText("92,082");
});
test("cross-year heatmap states and one tab stop with arrow navigation", async ({ page }) => {
  await page.goto(scope("/analytics","2023-07-01","2024-03-31"));
  const outside=page.getByRole("button",{name:"Jan 2023: Not in selected period",exact:true});
  await expect(outside).toBeVisible();
  await expect(page.locator('button[data-month][tabindex="0"]')).toHaveCount(1);
  await outside.focus(); await page.keyboard.press("ArrowRight");
  await expect(page.getByRole("button",{name:"Feb 2023: Not in selected period",exact:true})).toBeFocused();
  await page.keyboard.press("Enter");
  await expect(page.getByText("Not in selected period.",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Years",exact:true}).click();
  await expect(page.locator("table").last()).toContainText("Jul–Dec");
});
test("delayed stale requests cannot label NSW values as VIC, and retry retains scope", async ({ page }) => {
  await page.goto(scope());
  await expect(page.locator(".metric-value").first()).toHaveText("18,939");
  await page.route("**/api/data/**", async route => {
    const u=new URL(route.request().url());
    if(u.searchParams.get("source")==="VIC") { await new Promise(resolve=>setTimeout(resolve,700)); }
    await route.continue().catch(()=>{});
  });
  await page.getByLabel("Data source",{exact:true}).click();
  await page.getByRole("option", { name: "VIC", exact: true }).click();
  await expect(page.locator(".metric-value").first()).toHaveText("—");
  await expect(page.getByRole("button",{name:"Crashes definition",exact:true})).toBeDisabled();
  await page.getByLabel("Data source",{exact:true}).click();
  await page.getByRole("option", { name: "QLD", exact: true }).click();
  await expect(page.locator(".metric-value").first()).toHaveText("14,358");
  await page.unroute("**/api/data/**");
  let failed=false;
  await page.route("**/api/data/overview?**",async route=>{if(!failed){failed=true;await route.fulfill({status:503,body:"unavailable"});}else await route.continue();});
  await page.getByLabel("Data source",{exact:true}).click();
  await page.getByRole("option", { name: "NSW", exact: true }).click();
  await expect(page.locator(".error-banner")).toContainText("could not be loaded");
  await expect(page.getByText("Map unavailable. Retry this selection above.")).toBeVisible();
  await page.getByRole("button",{name:"Retry selection"}).click();
  await expect(page.locator(".metric-value").first()).toHaveText("18,939");
  await expect(page.getByLabel("Data source",{exact:true})).toHaveText("NSW");
});
test("390px dark/light, source severity restore, numeric map legend and no coverage", async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await page.goto(scope("/analytics"));
  await expect(page.getByTestId("analytics-total")).toHaveText("18,939");
  await page.getByRole("button",{name:"Use full-period selection"}).click();
  await expect(page.getByRole("button",{name:"Share",exact:true})).toBeEnabled();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
  await page.getByRole("button",{name:/Switch to light theme/}).click();
  await page.reload();
  await expect(page.getByRole("button",{name:/Switch to dark theme/})).toBeVisible();
  await page.goto(scope("/","2025-01-01","2025-12-31"));
  await expect(page.getByText("No observations in this project snapshot cover the selected months.").first()).toBeVisible();
  await expect(page.locator(".legend-ends")).toHaveCount(0);
  await page.getByRole("button",{name:"Reset dates",exact:true}).click();
  await expect(page.locator(".metric-value").first()).toHaveText("92,082");
  await expect(page.getByText(/Relative to current selection/)).toBeVisible();
  await expect(page.getByText("Loading chart",{exact:true})).toHaveCount(0);
  await page.waitForLoadState("networkidle");
  await page.screenshot({path:"output/playwright/dashboard-trust-mobile.png",fullPage:true});
});
test("heatmap visibly distinguishes known zero, unknown, no coverage and outside selection", async ({page}) => {
  await page.route("**/api/data/overview?**", async route => {
    const response=await route.fetch(); const body=await response.json();
    body.data.crashes.value=null; body.data.crashes.availability="unknown";
    await route.fulfill({response,json:body});
  });
  await page.route("**/api/data/timeseries?**",async route=>{
    const response=await route.fetch(); const body=await response.json();
    body.data=body.data.map((row: {period:string;crashes:number|null})=>row.period==="2020-01"?{...row,crashes:0}:row.period==="2020-02"?{...row,crashes:null}:row);
    await route.fulfill({response,json:body});
  });
  await page.goto(scope("/analytics","2019-12-01","2020-02-29"));
  await expect(page.getByRole("button",{name:"Dec 2019: No coverage",exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Jan 2020: 0 crashes",exact:true})).toHaveText("0");
  await expect(page.getByRole("button",{name:"Feb 2020: Unknown count",exact:true})).toHaveText("?");
  await expect(page.getByRole("button",{name:"Mar 2020: Not in selected period",exact:true})).toHaveText("Out");
});
test("stable desktop source tabs, compact mobile analytics and data evidence render",async ({page})=>{
  await page.goto("/?datasetVersion=official-v1&batchId=bcc5da57-25f2-41ec-9925-bef421b02671");
  await expect(page.locator(".metric-by-source").first()).toContainText("92,082");
  await expect(page.getByText("Loading chart",{exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"QLD",exact:true}).click();
  await expect(page.getByRole("button",{name:"QLD",exact:true})).toHaveAttribute("aria-pressed","true");
  await page.waitForLoadState("networkidle");
  await page.screenshot({path:"output/playwright/dashboard-trust-desktop.png",fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.goto(scope("/analytics","2024-03-01","2024-03-31","&metric=livesLost"));
  await expect(page.getByRole("heading",{name:"Mar 2024 details"})).toBeVisible();
  await expect(page.locator(".analytics-chart canvas").first()).toBeVisible();
  await page.waitForLoadState("networkidle");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
  await page.screenshot({path:"output/playwright/dashboard-trust-analytics-mobile.png",fullPage:true});
  await page.getByRole("link",{name:"Data",exact:true}).click();
  await expect(page.getByRole("region",{name:"Coverage and interpretation"})).toContainText("2,365");
  await expect(page.getByRole("region",{name:"Coverage and interpretation"})).toContainText("not all road crashes");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
});
